@startuml "Architecture"

cloud "Authentication\nMicroservice" as AS1 {
    [Auth] as AS1A
    () "HTTP" as AS1I
    AS1A - AS1I
}
database "Authentication\nDatabase" {
    [AuthDB]
}

cloud "Calendar\nMicroservice" AS CS1 {
    [Calendar] as CS1C
    () "HTTP" as CS1I
    CS1C - CS1I
}

database "Calendar\nDatabase" {
    [CalendarDB]
}
node "API Gateway" {
    () "HTTP" as AGI
    AGI - [Gateway]
}

AS1A -- [AuthDB]
CS1C -- [CalendarDB]
AGI - AS1I
AGI - CS1I
[GUI] -- AGI
@enduml