@startuml "Calendar Database Models"

object "Calendars" as C {
    <PK> **calendar_id**: //Integer//
    owner: //String//
}

object "CalendarSharingRelationship" as CSR {
    <FK> **calendar_id**: //Integer//
    <FK> **shared_calendar_id**: //Integer//
}

object "CalendarEventsRelationship" as CER {
    <FK> **calendar_id**: //Integer//
    <FK> **event_id**: //Integer//
}

object "Events" as E {
    <PK> **event_id**: //Integer//
    title: //String//
    date: //String//
    organizer: //String//
    public: //Boolean//
}

object "Invites" as I {
    <PK> **invite_id**: //Integer//
    <FK> event_id: //Integer//
    <FK> calendar_id: //Integer//
    status: //String//
}

' The calendars who you shared with
C "*" -- "*" CSR
' The (maybe) participating events
C "*" -- "*" CER
E "*" -- "*" CER
' The invites of an event
E "1" -- "*" I
C "1" -- "*" I

@enduml